### ISSUE TITLE
Typo in functions.py line 291

### ISSUE THREAD

**Issue by cyb3rwr3ck** [threatexpress/random_c2_profile#1]
Line contains `return str(random.randint(1,4=5)` which ends up in:

```
random_c2_profile/core/functions.py", line 291
    return str(random.randint(1,4=5))
                                ^
SyntaxError: expression cannot contain assignment, perhaps you meant "=="?

```
Probably you intended to type _4*5_ (for whatever reason)?

**Comment by aancw** [comment]
It's fixed https://github.com/threatexpress/random_c2_profile/blob/d3f75aa06c3f4c39f8c01a7ff4c1a89ed521b3be/core/functions.py#L291

e03e24c622564264750d1aed7916bed80e57c79e
