### ISSUE TITLE
Downgrade markupsafe

### ISSUE THREAD

**Issue by apache-strike** [threatexpress/random_c2_profile#3]
Hi,

Just a little update ^^
Since the version 2.1.0 of markupsafe they removed soft_unicode.
Release note: https://markupsafe.palletsprojects.com/en/2.1.x/changes/#version-2-1-0
You can add in requirements.txt:
markupsafe==2.0.1

cheers

**Comment by vestjoe** [comment]
k

**Comment by quantumburnz** [comment]
Hi @vestjoe - not sure if you meant to make this change in your last commit a few days ago but the issue still remains and requirements.txt needs to be updated as @apache-strike mentioned. Thanks for your hard work on this project!

**Comment by vestjoe** [comment]
I think this is fixed now. I tweaked the pipenv settings and updated dependencies to the latest versions.
