### ISSUE TITLE
random HTTP content is not OPSEC safe

### ISSUE THREAD

**Issue by superuser5** [threatexpress/random_c2_profile#9]
Hello,

thanks for the great project.

the get_http_content() function returns non OPSEC safe HTTP blob. 
https://github.com/threatexpress/random_c2_profile/blob/cb71b2e972a15df759caf7b8bd9264a0dbdcee5d/core/functions.py#L91

Thanks

**Comment by vestjoe** [comment]
I'm updating now for 4.7, but 1. This was designed to be a generic randomizer to help bootstrap a template. You can tweak as you'd like. 2. What specifically is not OPSEC safe?

**Comment by superuser5** [comment]
Thank you for updating the tool. I was referring to that jquery blob and the get_process_inject_execute could put CreateRemoteThread in first and is heavily detected.

**Comment by superuser5** [comment]
thank you for improving the get_http_content, closing the issue
